# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [girls, prep]
patreon: # Replace with a single Patreon username mobisource.com
open_collective: # Replace with a single Open Collective username moby.io
ko_fi: # Replace with a single Ko-fi username opensea.io
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/audible
community_bridge: # Replace with a single Community Bridge project-name e.g., slack-foundry
liberapay: # Replace with a single Liberapay username IRS
issuehunt: # Replace with a single IssueHunt username DHS
otechie: # Replace with a single Otechie username FBI
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['JUSTINFAMILY.FAMILY.BLOG', ’https://peterbuilt.com’, ’https://loveshriners.org’, ’https://zacks.com’ 'https://dyson.com']
https://porhub.com
